# Generated by Django 4.2 on 2024-03-17 03:25

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('instructions', django_summernote.fields.SummernoteTextField(max_length=10000)),
                ('ingredients', django_summernote.fields.SummernoteTextField(max_length=10000)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_alt', models.CharField(max_length=100)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='breakfast', max_length=50)),
                ('cuisine_types', models.CharField(choices=[('african', 'African'), ('american', 'American'), ('caribbean', 'Caribbean'), ('asian', 'Asian'), ('middle_eastern', 'Middle Eastern'), ('chinese', 'Chinese'), ('indian', 'Indian'), ('pakistani', 'Pakistani'), ('indonesian', 'Indonesian'), ('european', 'European'), ('oceanic', 'Oceanic')], default='african', max_length=50)),
                ('calories', models.IntegerField()),
                ('posted_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
    ]
